style="conventional"
ignore_author_re="(dependabot|renovate)"
merge_commit = false
subject_capitalized = false
allowed_types = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"]