allowed_types = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "refactor",
  "revert",
  "style",
  "test",
]

ignore_author_re    = "(dependabot|renovate)"
imperative_subject  = false
merge_commit        = false
style               = "conventional"
subject_capitalized = false
