verbose = true

['esacteksab/go-project-template']
  path  = '/home/bmorriso/local-repo/projects/projectTemplates/go-project-template'
  files = ['.editorconfig', '.gitignore', 'package.json', '.prettierrc']

['esacteksab/.github']
  path  = '/home/bmorriso/local-repo/projects/esacteksab-github'
  files = ['.github/workflows/spelling.yml', '.github/workflows/pre-commit.yml']

['esacteksab/gh-tp']
  path  = '/home/bmorriso/local-repo/projects/tp/gh-tp'
  files = ['.github/workflows/test.yml']
