name: Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR type
        run: |
          echo "${{ github.event.pull_request.title }}" | cut -d':' -f1
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
