name: Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Get PR type and add label
        run: |
          gh auth setup-git
          PRTITLE="${{ github.event.pull_request.title }}"
          REGEX="\(([^)]+)\)"
          if [[ ${PRTITLE} =~ ${REGEX} ]]; then
            SCOPE="${BASH_REMATCH[1]}"
            TYPE="$(echo ${PRTITLE} | cut -d'(' -f1)"
          else
            TYPE="$(echo "${PRTITLE}" | cut -d':' -f1)"
          fi

          if [[ ${SCOPE} == "deps" ]]; then
            gh pr edit 5 --add-label "type: ${TYPE},type: dependencies"
          else
            gh pr edit 5 --add-label "type: ${TYPE}"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
