name: Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR type
        run: |
          TYPE="echo ${{ github.event.pull_request.title }} | cut -d':' -f1"
          gh pr edit --add-label "type: ${TYPE}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
